const ActionTypes = {
  INVALIDATE_TOPICLIST: 'INVALIDATE_TOPICLIST',
  REQUEST_TOPICLIST: 'REQUEST_TOPICLIST',
  RECEIVE_TOPICLIST: 'RECEIVE_TOPICLIST',

  REQUEST_TOPIC: 'REQUEST_TOPIC',
  RECEIVE_TOPIC: 'RECEIVE_TOPIC',
  RESET_TOPIC: 'RESET_TOPIC',

  INVALIDATE_FORUM: 'INVALIDATE_FORUM',
  REQUEST_FORUM: 'REQUEST_FORUM',
  RECEIVE_FORUM: 'RECEIVE_FORUM',

  SET_AUTHRIZATION: 'SET_AUTHRIZATION',

  REQUEST_LOGIN: 'REQUEST_LOGIN',
  RECEIVE_LOGIN: 'RECEIVE_LOGIN',

  REQUEST_LOGOUT: 'REQUEST_LOGOUT',
};

export default ActionTypes;
