const ActionTypes = {
  INVALIDATE_TOPIC: 'INVALIDATE_TOPIC',
  REQUEST_TOPIC: 'REQUEST_TOPIC',
  RECEIVE_TOPIC: 'RECEIVE_TOPIC',

  INVALIDATE_FORUM: 'INVALIDATE_FORUM',
  REQUEST_FORUM: 'REQUEST_FORUM',
  RECEIVE_FORUM: 'RECEIVE_FORUM'
};

export default ActionTypes;
