module.exports = {
  INVALIDATE_TOPICLIST: 'INVALIDATE_TOPICLIST',
  REQUEST_TOPICLIST: 'REQUEST_TOPICLIST',
  RECEIVE_TOPICLIST: 'RECEIVE_TOPICLIST',
  RESET_TOPICLIST: 'RESET_TOPICLIST',
  FAILURE_TOPICLIST: 'FAILURE_TOPICLIST',

  INVALIDATE_SEARCH: 'INVALIDATE_SEARCH',
  REQUEST_SEARCH: 'REQUEST_SEARCH',
  RECEIVE_SEARCH: 'RECEIVE_SEARCH',
  RESET_SEARCH: 'RESET_SEARCH',
  FAILURE_SEARCH: 'FAILURE_SEARCH',

  REQUEST_TOPIC: 'REQUEST_TOPIC',
  RECEIVE_TOPIC: 'RECEIVE_TOPIC',
  RESET_TOPIC: 'RESET_TOPIC',
  FAILURE_TOPIC: 'FAILURE_TOPIC',

  START_PUBLISH: 'START_PUBLISH',
  FINISH_PUBLISH: 'FINISH_PUBLISH',
  RESET_PUBLISH: 'RESET_PUBLISH',
  FAILURE_PUBLISH: 'FAILURE_PUBLISH',

  START_REPLY: 'START_REPLY',
  FINISH_REPLY: 'FINISH_REPLY',
  RESET_REPLY: 'RESET_REPLY',
  FAILURE_REPLY: 'FAILURE_REPLY',

  START_VOTE: 'START_VOTE',
  FINISH_VOTE: 'FINISH_VOTE',
  RESET_VOTE: 'RESET_VOTE',
  FAILURE_VOTE: 'FAILURE_VOTE',

  INVALIDATE_FORUMLIST: 'INVALIDATE_FORUMLIST',
  REQUEST_FORUMLIST: 'REQUEST_FORUMLIST',
  REQUEST_SUBFORUMLIST: 'REQUEST_SUBFORUMLIST',
  RECEIVE_FORUMLIST: 'RECEIVE_FORUMLIST',
  FAILURE_FORUMLIST: 'FAILURE_FORUMLIST',

  SET_AUTHRIZATION: 'SET_AUTHRIZATION',
  RESET_AUTHRIZATION: 'RESET_AUTHRIZATION',
  RESET_AUTHRIZATION_RESULT: 'RESET_AUTHRIZATION_RESULT',

  INVALIDATE_NOTIFYLIST: 'INVALIDATE_NOTIFYLIST',
  REQUEST_NOTIFYLIST_AT: 'REQUEST_NOTIFYLIST_AT',
  REQUEST_NOTIFYLIST_REPLY: 'REQUEST_NOTIFYLIST_REPLY',
  RECEIVE_NOTIFYLIST: 'RECEIVE_NOTIFYLIST',
  FAILURE_NOTIFYLIST: 'FAILURE_NOTIFYLIST',

  REQUEST_LOGIN: 'REQUEST_LOGIN',
  RECEIVE_LOGIN: 'RECEIVE_LOGIN',
  FAILURE_LOGIN: 'FAILURE_LOGIN',

  REMOVE_CACHE: 'REMOVE_CACHE'
};
