const ActionTypes = {
  INVALIDATE_TOPICLIST: 'INVALIDATE_TOPICLIST',
  REQUEST_TOPICLIST: 'REQUEST_TOPICLIST',
  RECEIVE_TOPICLIST: 'RECEIVE_TOPICLIST',

  REQUEST_TOPIC: 'REQUEST_TOPIC',
  RECEIVE_TOPIC: 'RECEIVE_TOPIC',
  RESET_TOPIC: 'RESET_TOPIC',

  START_PUBLISH: 'START_PUBLISH',
  FINISH_PUBLISH: 'FINISH_PUBLISH',
  RESET_PUBLISH: 'RESET_PUBLISH',

  INVALIDATE_FORUMLIST: 'INVALIDATE_FORUMLIST',
  REQUEST_FORUMLIST: 'REQUEST_FORUMLIST',
  RECEIVE_FORUMLIST: 'RECEIVE_FORUMLIST',

  SET_AUTHRIZATION: 'SET_AUTHRIZATION',
  RESET_AUTHRIZATION: 'RESET_AUTHRIZATION',

  REQUEST_LOGIN: 'REQUEST_LOGIN',
  RECEIVE_LOGIN: 'RECEIVE_LOGIN',

  REQUEST_LOGOUT: 'REQUEST_LOGOUT',

  CHANGE_ROUTE: 'CHANGE_ROUTE',
};

export default ActionTypes;
